name: reweight
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - pip
  - pytest
  - torch
  - policyengine_core
  - policyengine_us
  - policyengine_uk
  - matplotlib
  - pip:
      - jupyter-book
